# Generated by Django 5.2.15 on 2026-06-22 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_jobapplication_assigned_interviewer"),
        ("interviews", "0002_alter_calendarevent_calendar_link"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="scheduling_method",
            field=models.CharField(
                choices=[("manual", "Manual"), ("self_scheduled", "Self Scheduled")],
                default="manual",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="InterviewerAvailabilitySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interviewer",
                    models.ForeignKey(
                        limit_choices_to={"role": "interviewer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviewer_availability_slots",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["start_datetime"],
            },
        ),
        migrations.AddField(
            model_name="interview",
            name="availability_slot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interview",
                to="interviews.intervieweravailabilityslot",
            ),
        ),
        migrations.CreateModel(
            name="InterviewSchedulingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remark", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_scheduling_requests",
                        to="applications.jobapplication",
                    ),
                ),
                (
                    "interview",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduling_request",
                        to="interviews.interview",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        limit_choices_to={"role": "interviewer"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interview_scheduling_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_scheduling_requests",
                        to="organizations.organization",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        limit_choices_to={"role": "recruiter"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_interview_scheduling_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_slot",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduling_request",
                        to="interviews.intervieweravailabilityslot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="intervieweravailabilityslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_datetime__gt", models.F("start_datetime"))),
                name="availability_slot_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="intervieweravailabilityslot",
            constraint=models.UniqueConstraint(
                fields=("interviewer", "start_datetime", "end_datetime"),
                name="unique_interviewer_availability_slot",
            ),
        ),
    ]
