# Generated by Django 5.2.15 on 2026-06-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0003_interview_scheduling_method_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interviewstatushistory",
            options={
                "ordering": ["-changed_at"],
                "verbose_name": "Interview status history",
                "verbose_name_plural": "Interview status histories",
            },
        ),
    ]
