# Generated by Django 5.2.15 on 2026-06-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0005_backfill_scheduling_request_interviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("scheduled", "Scheduled"),
                    ("declined", "Declined"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="assigned",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="interviewstatushistory",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("scheduled", "Scheduled"),
                    ("declined", "Declined"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="interviewstatushistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("scheduled", "Scheduled"),
                    ("declined", "Declined"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=30,
            ),
        ),

        migrations.AlterField(
            model_name="interview",
            name="scheduling_method",
            field=models.CharField(
                choices=[("self_scheduled", "Self Scheduled")],
                default="self_scheduled",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="InterviewInvitation",
        ),
    ]
