# Generated by Django 5.2.15 on 2026-06-24 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_alter_applicationstagehistory_options"),
        ("interviews", "0006_alter_interview_status_and_more"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewerAvailabilityPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_duration_minutes", models.PositiveSmallIntegerField(default=30)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("physical", "Physical"),
                            ("phone", "Phone"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("meeting_link", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("effective_from", models.DateField()),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="InterviewerUnavailableDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="interview",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interview",
            name="interview_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interview",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="interview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["assigned", "scheduled"])),
                fields=("interviewer", "interview_date", "start_time", "end_time"),
                name="unique_active_interview_booking_time",
            ),
        ),
        migrations.AddField(
            model_name="intervieweravailabilitypattern",
            name="interviewer",
            field=models.ForeignKey(
                limit_choices_to={"role": "interviewer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_patterns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="intervieweravailabilitypattern",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviewer_availability_patterns",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="interviewerunavailabledate",
            name="interviewer",
            field=models.ForeignKey(
                limit_choices_to={"role": "interviewer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unavailable_dates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interviewerunavailabledate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviewer_unavailable_dates",
                to="organizations.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="intervieweravailabilitypattern",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="availability_pattern_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="intervieweravailabilitypattern",
            constraint=models.CheckConstraint(
                condition=models.Q(("slot_duration_minutes__gte", 1)),
                name="availability_pattern_positive_duration",
            ),
        ),
        migrations.AddConstraint(
            model_name="interviewerunavailabledate",
            constraint=models.UniqueConstraint(
                fields=("interviewer", "date"),
                name="unique_interviewer_unavailable_date",
            ),
        ),
    ]
