# Generated by Codex

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0009_alter_calendarevent_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='panel_interviewers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'interviewer'}, related_name='panel_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewschedulingrequest',
            name='panel_interviewers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'interviewer'}, related_name='panel_interview_scheduling_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
