name: hrrecruit_mobile
description: Flutter mobile app for HRRecruit job applicants.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  flutter_web_auth_2: ^4.1.0
  go_router: ^14.8.1
  provider: ^6.1.2
  file_picker: ^8.1.7
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
