# Generated by Django 5.2.16 on 2026-07-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_applicantresume_validation_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("applicant", "Applicant"),
                    ("recruiter", "Recruiter"),
                    ("interviewer", "Interviewer"),
                    ("hr_head", "Hiring Manager"),
                ],
                default="applicant",
                max_length=20,
            ),
        ),
    ]
