import { useEffect, useMemo, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, CircularProgress, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { Link as RouterLink } from 'react-router-dom';
import { getAssignedInterviews } from '../../api/client.js';
import InterviewerNav from './InterviewerNav.jsx';
import { candidateName, formatDateTime, getApiErrorMessage, jobTitle, latestInviteStatus, titleize } from './interviewerUtils.js';

export default function InterviewListPage() {
  const [interviews, setInterviews] = useState([]); const [filter, setFilter] = useState('all'); const [error, setError] = useState(''); const [isLoading, setIsLoading] = useState(true);
  useEffect(() => { getAssignedInterviews().then(setInterviews).catch((err) => setError(getApiErrorMessage(err, 'Unable to load interviews.'))).finally(() => setIsLoading(false)); }, []);
  const filtered = useMemo(() => interviews.filter((interview) => filter === 'all' || (filter === 'upcoming' ? ['assigned', 'invitation_sent', 'scheduled'].includes(interview.status) : interview.status === filter)), [filter, interviews]);
  return <Box><InterviewerNav /><Paper sx={{ p: 3 }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={2} sx={{ mb: 2 }}><Box><Typography variant="h5" sx={{ fontWeight: 700 }}>Interviews</Typography></Box><TextField select label="Filter" value={filter} onChange={(event) => setFilter(event.target.value)} sx={{ minWidth: 180 }}><MenuItem value="all">All</MenuItem><MenuItem value="upcoming">Upcoming</MenuItem><MenuItem value="completed">Completed</MenuItem><MenuItem value="declined">Declined</MenuItem><MenuItem value="cancelled">Cancelled</MenuItem></TextField></Stack>{error ? <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert> : null}{isLoading ? <CircularProgress /> : null}<Stack spacing={2}>{filtered.map((interview) => <Card key={interview.id} variant="outlined"><CardContent><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" spacing={1}><Box><Typography variant="h6">{candidateName(interview)} • {jobTitle(interview)}</Typography><Typography color="text.secondary">{titleize(interview.status)} • Invite: {latestInviteStatus(interview)} • {formatDateTime(interview.scheduled_datetime ?? interview.latest_invitation?.proposed_datetime)}</Typography><Typography color="text.secondary">{interview.mode} • {interview.meeting_link || interview.location || 'No venue yet'}</Typography></Box><Stack direction="row" spacing={1} useFlexGap flexWrap="wrap"><Button component={RouterLink} to={`/interviewer/interviews/${interview.id}`} variant="outlined">Detail</Button><Button component={RouterLink} to={`/interviewer/interviews/${interview.id}/recording`}>Upload</Button><Button component={RouterLink} to={`/interviewer/interviews/${interview.id}/evaluation`}>Evaluate</Button></Stack></Stack></CardContent></Card>)}{!isLoading && filtered.length === 0 ? <Typography color="text.secondary">No interviews found.</Typography> : null}</Stack></Paper></Box>;
}
