import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, CircularProgress, List, ListItem, ListItemText, Paper, Stack, Typography } from '@mui/material';
import { Link as RouterLink, useParams } from 'react-router-dom';
import { getInterview } from '../../api/client.js';
import InterviewerNav from './InterviewerNav.jsx';
import { candidateName, formatDateTime, getApiErrorMessage, jobTitle, titleize } from './interviewerUtils.js';

export default function InterviewDetailPage() {
  const { interviewId } = useParams(); const [interview, setInterview] = useState(null); const [error, setError] = useState(''); const [isLoading, setIsLoading] = useState(true);
  useEffect(() => { getInterview(interviewId).then(setInterview).catch((err) => setError(getApiErrorMessage(err, 'Unable to load interview detail.'))).finally(() => setIsLoading(false)); }, [interviewId]);
  return <Box><InterviewerNav /><Paper sx={{ p: 3 }}><Typography variant="h5" sx={{ fontWeight: 700 }}>Interview Detail</Typography>{error ? <Alert severity="error" sx={{ my: 2 }}>{error}</Alert> : null}{isLoading ? <CircularProgress /> : null}{interview ? <Stack spacing={2} sx={{ mt: 2 }}><Card variant="outlined"><CardContent><Typography variant="h6">{candidateName(interview)} • {jobTitle(interview)}</Typography><Typography>Status: {titleize(interview.status)}</Typography><Typography>Scheduled: {formatDateTime(interview.scheduled_datetime)}</Typography><Typography>Mode: {titleize(interview.mode)}</Typography><Typography>Meeting/Location: {interview.meeting_link || interview.location || '—'}</Typography><Typography>Recruiter remark: {interview.application?.recruiter_remark || '—'}</Typography></CardContent></Card><Stack direction="row" spacing={1} useFlexGap flexWrap="wrap"><Button component={RouterLink} to={`/interviewer/candidates/${interview.application?.id}`} variant="outlined">Candidate profile</Button><Button component={RouterLink} to={`/interviewer/interviews/${interview.id}/recording`} variant="outlined">Upload recording</Button><Button component={RouterLink} to={`/interviewer/interviews/${interview.id}/transcript-summary`} variant="outlined">Transcript & summary</Button><Button component={RouterLink} to={`/interviewer/interviews/${interview.id}/evaluation`} variant="outlined">Submit evaluation</Button></Stack><Card variant="outlined"><CardContent><Typography variant="h6">Status history</Typography><List dense>{interview.status_history?.map((item) => <ListItem key={item.id}><ListItemText primary={`${titleize(item.from_status)} → ${titleize(item.to_status)}`} secondary={`${item.note || 'No note'} • ${formatDateTime(item.changed_at)} • ${item.changed_by_name || 'System'}`} /></ListItem>)}</List>{!interview.status_history?.length ? <Typography color="text.secondary">No status history yet.</Typography> : null}</CardContent></Card></Stack> : null}</Paper></Box>;
}
