import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Paper, Stack, TextField, Typography } from '@mui/material';
import { useParams } from 'react-router-dom';
import { getInterview, submitInterviewEvaluation } from '../../api/client.js';
import InterviewerNav from './InterviewerNav.jsx';
import { candidateName, getApiErrorMessage, jobTitle } from './interviewerUtils.js';

export default function SubmitEvaluationPage() {
  const { interviewId } = useParams(); const [interview, setInterview] = useState(null); const [overallComment, setOverallComment] = useState(''); const [answers, setAnswers] = useState([{ criterion_id: '', score: '', comment: '' }]); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [isSaving, setIsSaving] = useState(false);
  useEffect(() => { getInterview(interviewId).then(setInterview).catch((err) => setError(getApiErrorMessage(err, 'Unable to load interview.'))); }, [interviewId]);
  const updateAnswer = (index, patch) => setAnswers((current) => current.map((answer, answerIndex) => (answerIndex === index ? { ...answer, ...patch } : answer)));
  const submit = async (event) => { event.preventDefault(); setError(''); setSuccess(''); setIsSaving(true); try { await submitInterviewEvaluation(interviewId, { overall_comment: overallComment, answers: answers.map((answer) => ({ criterion_id: Number(answer.criterion_id), score: answer.score, comment: answer.comment })) }); setSuccess('Evaluation submitted successfully.'); } catch (err) { setError(getApiErrorMessage(err, 'Unable to submit evaluation. Confirm the criterion IDs match the recruiter-configured form.')); } finally { setIsSaving(false); } };
  return <Box><InterviewerNav /><Paper sx={{ p: 3 }}><Typography variant="h5" sx={{ fontWeight: 700 }}>Submit Evaluation</Typography>{interview ? <Typography color="text.secondary" sx={{ mb: 2 }}>{candidateName(interview)} • {jobTitle(interview)}</Typography> : null}<Alert severity="info" sx={{ mb: 2 }}>Enter one answer for each recruiter-configured evaluation criterion. The backend validates criterion IDs, max scores, and duplicate answers.</Alert>{error ? <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert> : null}{success ? <Alert severity="success" sx={{ mb: 2 }}>{success}</Alert> : null}<Stack component="form" spacing={2} onSubmit={submit}><TextField label="Overall comment" multiline minRows={4} required value={overallComment} onChange={(event) => setOverallComment(event.target.value)} />{answers.map((answer, index) => <Card key={index} variant="outlined"><CardContent><Stack spacing={2}><Typography variant="subtitle1">Criterion answer {index + 1}</Typography><TextField label="Criterion ID" type="number" required value={answer.criterion_id} onChange={(event) => updateAnswer(index, { criterion_id: event.target.value })} /><TextField label="Score" type="number" required value={answer.score} onChange={(event) => updateAnswer(index, { score: event.target.value })} /><TextField label="Comment" multiline minRows={2} value={answer.comment} onChange={(event) => updateAnswer(index, { comment: event.target.value })} /></Stack></CardContent></Card>)}<Stack direction="row" spacing={1}><Button type="button" variant="outlined" onClick={() => setAnswers([...answers, { criterion_id: '', score: '', comment: '' }])}>Add answer</Button><Button type="button" variant="outlined" disabled={answers.length === 1} onClick={() => setAnswers(answers.slice(0, -1))}>Remove last</Button><Button type="submit" variant="contained" disabled={isSaving}>{isSaving ? 'Submitting…' : 'Submit evaluation'}</Button></Stack></Stack></Paper></Box>;
}
