import { useState } from 'react';
import {
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  Divider,
  Grid,
  List,
  ListItem,
  ListItemText,
  Paper,
  Stack,
  TextField,
  Typography,
} from '@mui/material';
import { useLocation, useParams } from 'react-router-dom';
import { generateTranscriptSummary, transcribeRecording, updateInterviewSummary } from '../../api/client.js';
import InterviewerNav from './InterviewerNav.jsx';
import {
  getApiErrorMessage,
  getStoredRecordingId,
  getStoredSummaryId,
  getStoredTranscriptId,
  setStoredSummaryId,
  setStoredTranscriptId,
} from './interviewerUtils.js';

const getSummaryTransparencyValue = (summary, key, fallback = '') => summary?.transparency?.[key] ?? summary?.summary_json?.[key] ?? fallback;

function SectionCard({ title, description, action, children }) {
  return (
    <Card variant="outlined">
      <CardContent>
        <Stack spacing={2}>
          <Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" spacing={1.5}>
            <Box>
              <Typography variant="h6" sx={{ fontWeight: 700 }}>
                {title}
              </Typography>
              {description ? (
                <Typography variant="body2" color="text.secondary">
                  {description}
                </Typography>
              ) : null}
            </Box>
            {action}
          </Stack>
          {children}
        </Stack>
      </CardContent>
    </Card>
  );
}

function MetadataChip({ label, value, color = 'default' }) {
  if (!value) return null;
  return <Chip size="small" color={color} label={`${label}: ${value}`} />;
}

function ReadOnlyBlock({ children }) {
  return (
    <Paper variant="outlined" sx={{ p: 1.5, bgcolor: 'grey.50' }}>
      <Typography variant="body2" whiteSpace="pre-line">
        {children || '—'}
      </Typography>
    </Paper>
  );
}

function SummaryTransparencyCard({ summary }) {
  if (!summary) return null;
  const provider = getSummaryTransparencyValue(summary, 'provider', 'unknown');
  const generationMode = getSummaryTransparencyValue(summary, 'generation_mode', 'unknown').replaceAll('_', ' ');
  const model = getSummaryTransparencyValue(summary, 'model', '');
  const limitations = getSummaryTransparencyValue(summary, 'limitations', []);

  return (
    <SectionCard
      title="AI transparency"
      description="A compact audit note showing how this draft was produced."
      action={(
        <Stack direction="row" spacing={1} useFlexGap flexWrap="wrap">
          <MetadataChip label="Provider" value={provider} color="primary" />
          <Chip size="small" label={generationMode} />
          <MetadataChip label="Model" value={model} />
        </Stack>
      )}
    >
      <Grid container spacing={2}>
        <Grid item xs={12} md={6}>
          <Alert severity="warning" variant="outlined">
            {getSummaryTransparencyValue(
              summary,
              'decision_boundary',
              'This AI summary supports interviewer review only and must not be treated as a final hiring decision.',
            )}
          </Alert>
        </Grid>
        <Grid item xs={12} md={6}>
          <Alert severity="success" variant="outlined">
            Generated by the configured real AI provider. If the provider is unavailable, this request fails instead of creating fake AI output.
          </Alert>
        </Grid>
      </Grid>

      <Box>
        <Typography variant="subtitle2" sx={{ mb: 0.75 }}>
          Evidence excerpt used by AI
        </Typography>
        <ReadOnlyBlock>{getSummaryTransparencyValue(summary, 'source_excerpt', 'No transcript excerpt available.')}</ReadOnlyBlock>
      </Box>

      <Box
        component="details"
        sx={{
          border: 1,
          borderColor: 'divider',
          borderRadius: 1,
          p: 1.5,
          '& summary': { cursor: 'pointer', fontWeight: 700 },
        }}
      >
        <summary>Known limitations</summary>
        <List dense sx={{ listStyleType: 'disc', pl: 3, pt: 1 }}>
          {(Array.isArray(limitations) && limitations.length ? limitations : ['Interviewer must verify the summary against the transcript.']).map((item) => (
            <ListItem key={item} sx={{ display: 'list-item', p: 0 }}>
              <ListItemText primary={item} />
            </ListItem>
          ))}
        </List>
      </Box>
    </SectionCard>
  );
}

function TranscriptPreview({ transcript }) {
  if (!transcript) return null;
  return (
    <SectionCard
      title={`Transcript #${transcript.id}`}
      description="Review the transcript before generating the AI summary."
      action={(
        <Stack direction="row" spacing={1} useFlexGap flexWrap="wrap">
          <MetadataChip label="Provider" value={transcript.transcript_json?.provider ?? 'unknown'} />
          <MetadataChip label="Model" value={transcript.transcript_json?.model} />
        </Stack>
      )}
    >
      <ReadOnlyBlock>{transcript.transcript_text}</ReadOnlyBlock>
    </SectionCard>
  );
}

function SummaryEditor({ summary, setSummary, isBusy, onSave }) {
  if (!summary) return null;
  return (
    <SectionCard
      title="Human review & edits"
      description="Edit the AI draft before using it for evaluation. HRRecruit keeps transparency metadata for audit."
    >
      <Alert severity="info" variant="outlined">
        Save only after verifying the draft against the transcript. AI text is decision support, not a final hiring decision.
      </Alert>
      <Grid container spacing={2}>
        <Grid item xs={12} md={6}>
          <TextField
            label="Strengths"
            multiline
            minRows={3}
            fullWidth
            value={summary.strengths ?? ''}
            onChange={(event) => setSummary({ ...summary, strengths: event.target.value })}
          />
        </Grid>
        <Grid item xs={12} md={6}>
          <TextField
            label="Weaknesses / follow-ups"
            multiline
            minRows={3}
            fullWidth
            value={summary.weaknesses ?? ''}
            onChange={(event) => setSummary({ ...summary, weaknesses: event.target.value })}
          />
        </Grid>
        <Grid item xs={12} md={4}>
          <TextField
            label="Communication score"
            type="number"
            fullWidth
            value={summary.communication_score ?? ''}
            onChange={(event) => setSummary({ ...summary, communication_score: event.target.value })}
            helperText="0-10 decision-support signal."
          />
        </Grid>
        <Grid item xs={12} md={8}>
          <TextField
            label="Overall impression"
            multiline
            minRows={2}
            fullWidth
            value={summary.overall_impression ?? ''}
            onChange={(event) => setSummary({ ...summary, overall_impression: event.target.value })}
          />
        </Grid>
        <Grid item xs={12}>
          <TextField
            label="Reviewed summary text"
            multiline
            minRows={5}
            fullWidth
            value={summary.editable_summary_text ?? ''}
            onChange={(event) => setSummary({ ...summary, editable_summary_text: event.target.value })}
          />
        </Grid>
      </Grid>
      <Button variant="contained" disabled={isBusy} onClick={onSave}>
        Save reviewed AI summary
      </Button>
    </SectionCard>
  );
}

export default function TranscriptSummaryPage() {
  const { interviewId } = useParams();
  const location = useLocation();
  const [recordingId, setRecordingId] = useState(String(location.state?.recordingId ?? getStoredRecordingId(interviewId)));
  const [transcriptId, setTranscriptId] = useState(getStoredTranscriptId(interviewId));
  const [summaryId, setSummaryId] = useState(getStoredSummaryId(interviewId));
  const [transcript, setTranscript] = useState(null);
  const [summary, setSummary] = useState(null);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [isBusy, setIsBusy] = useState(false);

  const makeTranscript = async () => {
    setError('');
    setSuccess('');
    setIsBusy(true);
    try {
      const data = await transcribeRecording(recordingId);
      setTranscript(data);
      setTranscriptId(String(data.id));
      setStoredTranscriptId(interviewId, data.id);
      setSuccess('Transcript generated by the configured real ASR provider.');
    } catch (err) {
      setError(getApiErrorMessage(err, 'Unable to generate transcript.'));
    } finally {
      setIsBusy(false);
    }
  };

  const makeSummary = async () => {
    setError('');
    setSuccess('');
    setIsBusy(true);
    try {
      const data = await generateTranscriptSummary(transcriptId);
      setSummary(data);
      setSummaryId(String(data.id));
      setStoredSummaryId(interviewId, data.id);
      setSuccess('AI summary generated with transparency metadata. Please review and edit before using it in evaluation.');
    } catch (err) {
      setError(getApiErrorMessage(err, 'Unable to generate AI summary.'));
    } finally {
      setIsBusy(false);
    }
  };

  const saveSummary = async () => {
    setError('');
    setSuccess('');
    setIsBusy(true);
    try {
      const editablePayload = {
        strengths: summary?.strengths ?? '',
        weaknesses: summary?.weaknesses ?? '',
        communication_score: summary?.communication_score ?? '',
        overall_impression: summary?.overall_impression ?? '',
        editable_summary_text: summary?.editable_summary_text ?? '',
      };
      const data = await updateInterviewSummary(summaryId, editablePayload);
      setSummary(data);
      setSuccess('AI summary edits saved. The transparency metadata remains available for audit/review.');
    } catch (err) {
      setError(getApiErrorMessage(err, 'Unable to update AI summary.'));
    } finally {
      setIsBusy(false);
    }
  };

  return (
    <Box>
      <InterviewerNav />
      <Paper sx={{ p: 3 }}>
        <Stack spacing={2}>
          <Box>
            <Typography variant="h5" sx={{ fontWeight: 700 }}>
              Transcript & AI Summary
            </Typography>
            <Typography color="text.secondary">
              Generate a transcript, create a transparent AI draft, then complete human review before evaluation.
            </Typography>
          </Box>

          {error ? <Alert severity="error">{error}</Alert> : null}
          {success ? <Alert severity="success">{success}</Alert> : null}

          <SectionCard
            title="1. Generate transcript"
            description="Use the latest uploaded recording, or open advanced IDs if you need to paste one manually."
            action={(
              <Button variant="contained" disabled={!recordingId || isBusy} onClick={makeTranscript}>
                Generate transcript
              </Button>
            )}
          >
            <Box
              component="details"
              sx={{
                border: 1,
                borderColor: 'divider',
                borderRadius: 1,
                p: 1.5,
                '& summary': { cursor: 'pointer', fontWeight: 700 },
              }}
            >
              <summary>Advanced recording ID</summary>
              <TextField
                label="Recording ID"
                value={recordingId}
                onChange={(event) => setRecordingId(event.target.value)}
                helperText="Auto-filled after upload on this browser; enter manually only if needed."
                fullWidth
                sx={{ mt: 1.5 }}
              />
            </Box>
          </SectionCard>

          <TranscriptPreview transcript={transcript} />

          <SectionCard
            title="2. Generate AI summary"
            description="The summary draft is created from a transcript and must be checked by the interviewer."
            action={(
              <Button variant="contained" disabled={!transcriptId || isBusy} onClick={makeSummary}>
                Generate AI summary
              </Button>
            )}
          >
            <Box
              component="details"
              sx={{
                border: 1,
                borderColor: 'divider',
                borderRadius: 1,
                p: 1.5,
                '& summary': { cursor: 'pointer', fontWeight: 700 },
              }}
            >
              <summary>Advanced transcript/summary IDs</summary>
              <Grid container spacing={2} sx={{ mt: 0.5 }}>
                <Grid item xs={12} md={6}>
                  <TextField
                    label="Transcript ID"
                    value={transcriptId}
                    onChange={(event) => setTranscriptId(event.target.value)}
                    fullWidth
                  />
                </Grid>
                <Grid item xs={12} md={6}>
                  <TextField
                    label="Summary ID"
                    value={summaryId}
                    onChange={(event) => setSummaryId(event.target.value)}
                    helperText="Used when saving edits to an existing draft."
                    fullWidth
                  />
                </Grid>
              </Grid>
            </Box>
          </SectionCard>

          {summary ? (
            <>
              <Divider />
              <SummaryTransparencyCard summary={summary} />
              <SummaryEditor summary={summary} setSummary={setSummary} isBusy={isBusy} onSave={saveSummary} />
            </>
          ) : null}
        </Stack>
      </Paper>
    </Box>
  );
}
