import { useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Paper, Stack, TextField, Typography } from '@mui/material';
import { useLocation, useParams } from 'react-router-dom';
import { generateTranscriptSummary, transcribeRecording, updateInterviewSummary } from '../../api/client.js';
import InterviewerNav from './InterviewerNav.jsx';
import { getApiErrorMessage, getStoredRecordingId, getStoredSummaryId, getStoredTranscriptId, setStoredSummaryId, setStoredTranscriptId } from './interviewerUtils.js';

export default function TranscriptSummaryPage() {
  const { interviewId } = useParams(); const location = useLocation();
  const [recordingId, setRecordingId] = useState(String(location.state?.recordingId ?? getStoredRecordingId(interviewId)));
  const [transcriptId, setTranscriptId] = useState(getStoredTranscriptId(interviewId));
  const [summaryId, setSummaryId] = useState(getStoredSummaryId(interviewId));
  const [transcript, setTranscript] = useState(null); const [summary, setSummary] = useState(null); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [isBusy, setIsBusy] = useState(false);
  const makeTranscript = async () => { setError(''); setSuccess(''); setIsBusy(true); try { const data = await transcribeRecording(recordingId); setTranscript(data); setTranscriptId(String(data.id)); setStoredTranscriptId(interviewId, data.id); setSuccess('Mock transcript generated.'); } catch (err) { setError(getApiErrorMessage(err, 'Unable to generate transcript.')); } finally { setIsBusy(false); } };
  const makeSummary = async () => { setError(''); setSuccess(''); setIsBusy(true); try { const data = await generateTranscriptSummary(transcriptId); setSummary(data); setSummaryId(String(data.id)); setStoredSummaryId(interviewId, data.id); setSuccess('Mock AI summary generated.'); } catch (err) { setError(getApiErrorMessage(err, 'Unable to generate AI summary.')); } finally { setIsBusy(false); } };
  const saveSummary = async () => { setError(''); setSuccess(''); setIsBusy(true); try { const data = await updateInterviewSummary(summaryId, summary); setSummary(data); setSuccess('AI summary edits saved.'); } catch (err) { setError(getApiErrorMessage(err, 'Unable to update AI summary.')); } finally { setIsBusy(false); } };
  return <Box><InterviewerNav /><Paper sx={{ p: 3 }}><Typography variant="h5" sx={{ fontWeight: 700 }}>Transcript & AI Summary</Typography><Typography color="text.secondary" sx={{ mb: 2 }}>Generate deterministic mock transcript and AI summary, then edit the AI summary before final evaluation.</Typography>{error ? <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert> : null}{success ? <Alert severity="success" sx={{ mb: 2 }}>{success}</Alert> : null}<Stack spacing={2}><TextField label="Recording ID" value={recordingId} onChange={(event) => setRecordingId(event.target.value)} helperText="Auto-filled after upload on this browser; enter manually if needed." /><Button variant="contained" disabled={!recordingId || isBusy} onClick={makeTranscript}>Generate mock transcript</Button>{transcript ? <Card variant="outlined"><CardContent><Typography variant="h6">Transcript #{transcript.id}</Typography><Typography whiteSpace="pre-line">{transcript.transcript_text}</Typography></CardContent></Card> : null}<TextField label="Transcript ID" value={transcriptId} onChange={(event) => setTranscriptId(event.target.value)} /><Button variant="contained" disabled={!transcriptId || isBusy} onClick={makeSummary}>Generate mock AI summary</Button>{summary ? <Card variant="outlined"><CardContent><Stack spacing={2}><TextField label="Strengths" multiline minRows={2} value={summary.strengths ?? ''} onChange={(event) => setSummary({ ...summary, strengths: event.target.value })} /><TextField label="Weaknesses" multiline minRows={2} value={summary.weaknesses ?? ''} onChange={(event) => setSummary({ ...summary, weaknesses: event.target.value })} /><TextField label="Communication score" type="number" value={summary.communication_score ?? ''} onChange={(event) => setSummary({ ...summary, communication_score: event.target.value })} /><TextField label="Overall impression" multiline minRows={2} value={summary.overall_impression ?? ''} onChange={(event) => setSummary({ ...summary, overall_impression: event.target.value })} /><TextField label="Editable summary text" multiline minRows={4} value={summary.editable_summary_text ?? ''} onChange={(event) => setSummary({ ...summary, editable_summary_text: event.target.value })} /><Button variant="outlined" disabled={isBusy} onClick={saveSummary}>Save AI summary edits</Button></Stack></CardContent></Card> : <TextField label="Summary ID" value={summaryId} onChange={(event) => setSummaryId(event.target.value)} helperText="Generate a new summary above to edit it in this page." />}</Stack></Paper></Box>;
}
