# Generated by Codex for production-like demo billing lifecycle metadata.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_seed_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_reason',
            field=models.CharField(
                choices=[
                    ('subscription_create', 'Subscription created'),
                    ('subscription_update', 'Subscription updated'),
                    ('renewal', 'Subscription renewal'),
                    ('manual', 'Manual adjustment'),
                ],
                default='subscription_create',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='hosted_invoice_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_url',
            field=models.URLField(blank=True),
        ),
    ]
