import { useEffect, useState } from 'react';
import { Alert, Box, Button, Paper, Stack, TextField, Typography } from '@mui/material';
import { useNavigate, useParams } from 'react-router-dom';
import { createJobEvaluationForm, getJob } from '../../api/client.js';
import RecruiterNav from './RecruiterNav.jsx';
import { getApiErrorMessage } from './recruiterUtils.js';

const blank = { criterion_name: '', description: '', max_score: '10.00', weight_score: '0.25' };
export default function EvaluationFormBuilderPage() {
  const { jobId } = useParams(); const navigate = useNavigate(); const [title, setTitle] = useState('Interview Evaluation Form'); const [criteria, setCriteria] = useState([blank]); const [existing, setExisting] = useState(null); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  useEffect(() => { getJob(jobId).then((job) => { if (job.interview_evaluation_form) { setExisting(job.interview_evaluation_form); setTitle(job.interview_evaluation_form.title); setCriteria(job.interview_evaluation_form.criteria ?? []); } }).catch((err) => setError(getApiErrorMessage(err, 'Unable to load evaluation form.'))); }, [jobId]);
  const update = (index, field, value) => setCriteria((items) => items.map((item, i) => i === index ? { ...item, [field]: value } : item));
  const save = async (event) => { event.preventDefault(); setError(''); setSuccess(''); try { await createJobEvaluationForm(jobId, { title, criteria }); setSuccess('Evaluation form created.'); setExisting({ title, criteria }); } catch (err) { setError(getApiErrorMessage(err, 'Unable to create evaluation form.')); } };
  return <Box><RecruiterNav /><Paper sx={{ p: 3 }}><Typography variant="h5" sx={{ fontWeight: 700 }}>Evaluation form builder</Typography><Typography color="text.secondary" sx={{ mb: 2 }}>Define interviewer scoring criteria. Existing forms are displayed read-only because the current backend supports creation once.</Typography>{error ? <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert> : null}{success ? <Alert severity="success" sx={{ mb: 2 }}>{success}</Alert> : null}<Box component="form" onSubmit={save}><Stack spacing={2}><TextField disabled={Boolean(existing)} label="Form title" value={title} onChange={(e) => setTitle(e.target.value)} />{criteria.map((criterion, index) => <Paper key={index} variant="outlined" sx={{ p: 2 }}><Stack spacing={2}><TextField disabled={Boolean(existing)} label="Criterion name" required value={criterion.criterion_name} onChange={(e) => update(index, 'criterion_name', e.target.value)} /><TextField disabled={Boolean(existing)} label="Description" required value={criterion.description} onChange={(e) => update(index, 'description', e.target.value)} /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField disabled={Boolean(existing)} label="Max score" type="number" value={criterion.max_score} onChange={(e) => update(index, 'max_score', e.target.value)} /><TextField disabled={Boolean(existing)} label="Weight" type="number" value={criterion.weight_score} onChange={(e) => update(index, 'weight_score', e.target.value)} /></Stack>{!existing ? <Button color="error" disabled={criteria.length === 1} onClick={() => setCriteria((items) => items.filter((_, i) => i !== index))}>Remove</Button> : null}</Stack></Paper>)}<Stack direction="row" spacing={1}>{!existing ? <Button onClick={() => setCriteria((items) => [...items, blank])} variant="outlined">Add criterion</Button> : null}{!existing ? <Button type="submit" variant="contained">Create form</Button> : null}<Button onClick={() => navigate(`/recruiter/jobs/${jobId}`)}>Back to job</Button></Stack></Stack></Box></Paper></Box>;
}
