import { useEffect, useState } from 'react';
import { Alert, Box, Button, Chip, CircularProgress, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useParams } from 'react-router-dom';
import { getApplications, submitHiringDecision } from '../../api/client.js';
import RecruiterNav from './RecruiterNav.jsx';
import { applicationName, getApiErrorMessage, scoreText, titleize } from './recruiterUtils.js';

export default function HiringDecisionPage() {
  const { applicationId } = useParams(); const [applications, setApplications] = useState([]); const [selectedId, setSelectedId] = useState(applicationId ?? ''); const [decision, setDecision] = useState('hire'); const [justification, setJustification] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [isLoading, setIsLoading] = useState(true);
  useEffect(() => { getApplications().then((items) => { setApplications(items); if (!applicationId && items[0]) setSelectedId(String(items[0].id)); }).catch((err) => setError(getApiErrorMessage(err, 'Unable to load applications.'))).finally(() => setIsLoading(false)); }, [applicationId]);
  const submit = async (event) => { event.preventDefault(); setError(''); setSuccess(''); try { const result = await submitHiringDecision(selectedId, { decision, justification }); setSuccess(`Hiring decision #${result.id} submitted for HR approval.`); } catch (err) { setError(getApiErrorMessage(err, 'Unable to submit hiring decision.')); } };
  const selected = applications.find((item) => String(item.id) === String(selectedId));
  return <Box><RecruiterNav /><Paper sx={{ p: 3 }}><Typography variant="h5" sx={{ fontWeight: 700 }}>Hiring decision</Typography><Typography color="text.secondary" sx={{ mb: 2 }}>Submit hire or reject recommendation for HR approval. AI supports the decision but does not finalize it.</Typography>{error ? <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert> : null}{success ? <Alert severity="success" sx={{ mb: 2 }}>{success}</Alert> : null}{isLoading ? <CircularProgress /> : <Stack spacing={3}><Box component="form" onSubmit={submit}><Stack spacing={2}><TextField label="Candidate" select required value={selectedId} onChange={(e) => setSelectedId(e.target.value)}>{applications.map((app) => <MenuItem key={app.id} value={app.id}>{applicationName(app)} — {app.job_title}</MenuItem>)}</TextField>{selected ? <Alert severity="info">Status: {titleize(selected.status)} • Final AI score: {scoreText(selected.final_score)}</Alert> : null}<TextField label="Decision" select value={decision} onChange={(e) => setDecision(e.target.value)}><MenuItem value="hire">Recommend hire</MenuItem><MenuItem value="reject">Recommend reject</MenuItem></TextField><TextField label="Justification for HR" required multiline minRows={4} value={justification} onChange={(e) => setJustification(e.target.value)} /><Button type="submit" variant="contained">Submit for HR approval</Button></Stack></Box><Typography variant="h6">Recent applications</Typography><Table><TableHead><TableRow><TableCell>Candidate</TableCell><TableCell>Job</TableCell><TableCell>Status</TableCell><TableCell>Score</TableCell></TableRow></TableHead><TableBody>{applications.slice(0, 8).map((app) => <TableRow key={app.id}><TableCell>{applicationName(app)}</TableCell><TableCell>{app.job_title}</TableCell><TableCell><Chip label={titleize(app.status)} size="small" /></TableCell><TableCell>{scoreText(app.final_score)}</TableCell></TableRow>)}</TableBody></Table></Stack>}</Paper></Box>;
}
