import { useEffect, useState } from 'react';
import { Alert, Box, Button, CircularProgress, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { useNavigate, useParams } from 'react-router-dom';
import { assignInterviewer, getApplication, getOrganizationMembers } from '../../api/client.js';
import RecruiterNav from './RecruiterNav.jsx';
import { getApiErrorMessage } from './recruiterUtils.js';

export default function InterviewAssignmentPage() {
  const { applicationId } = useParams(); const navigate = useNavigate(); const [application, setApplication] = useState(null); const [interviewers, setInterviewers] = useState([]); const [interviewerId, setInterviewerId] = useState(''); const [remark, setRemark] = useState(''); const [createdInterview, setCreatedInterview] = useState(null); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [isLoading, setIsLoading] = useState(true);
  useEffect(() => { Promise.all([getApplication(applicationId), getOrganizationMembers('')]).then(([app, members]) => { setApplication(app); setInterviewerId(app.assigned_interviewer?.id ?? ''); setInterviewers(members.filter((member) => member.role === 'interviewer' && member.status === 'active' && member.user_id)); }).catch((err) => setError(getApiErrorMessage(err, 'Unable to load assignment data.'))).finally(() => setIsLoading(false)); }, [applicationId]);
  const assign = async (event) => { event.preventDefault(); setError(''); setSuccess(''); try { const interview = await assignInterviewer(applicationId, { interviewer_id: Number(interviewerId), remark }); setCreatedInterview(interview); setSuccess('Interviewer assigned and interview record created.'); } catch (err) { setError(getApiErrorMessage(err, 'Unable to assign interviewer.')); } };
  return <Box><RecruiterNav /><Paper sx={{ p: 3 }}><Typography variant="h5" sx={{ fontWeight: 700 }}>Assign interviewer</Typography>{error ? <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert> : null}{success ? <Alert severity="success" sx={{ mb: 2 }}>{success}</Alert> : null}{isLoading ? <CircularProgress /> : <Stack spacing={3}><Typography><strong>Candidate:</strong> {application?.applicant?.full_name} for {application?.job_title}</Typography><Box component="form" onSubmit={assign}><Stack spacing={2}><TextField label="Interviewer" select required value={interviewerId} onChange={(e) => setInterviewerId(e.target.value)}>{interviewers.map((member) => <MenuItem key={member.id} value={member.user_id}>{member.full_name} ({member.email})</MenuItem>)}</TextField><TextField label="Optional remark" multiline minRows={3} value={remark} onChange={(e) => setRemark(e.target.value)} /><Button type="submit" variant="contained">Assign interviewer</Button></Stack></Box><Paper variant="outlined" sx={{ p: 2 }}><Typography variant="h6">Next step</Typography><Typography color="text.secondary">Interview record {createdInterview ? `#${createdInterview.id}` : 'will be created after assignment'}. In this backend, only the assigned interviewer can send interview invitations from their portal.</Typography><Button disabled={!createdInterview} onClick={() => navigate('/recruiter/interviews')} sx={{ mt: 2 }} variant="outlined">View interviews</Button></Paper></Stack>}</Paper></Box>;
}
