import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, CircularProgress, List, ListItem, ListItemText, Paper, Stack, Typography } from '@mui/material';
import { Link as RouterLink } from 'react-router-dom';
import { getInterviewEvaluationDetail, getInterviews } from '../../api/client.js';
import RecruiterNav from './RecruiterNav.jsx';
import { formatDateTime, getApiErrorMessage } from './recruiterUtils.js';

export default function InterviewEvaluationDetailPage() {
  const [interviews, setInterviews] = useState([]); const [detail, setDetail] = useState(null); const [error, setError] = useState(''); const [isLoading, setIsLoading] = useState(true);
  useEffect(() => { getInterviews().then(setInterviews).catch((err) => setError(getApiErrorMessage(err, 'Unable to load interviews.'))).finally(() => setIsLoading(false)); }, []);
  const openDetail = async (interview) => { setDetail(null); setError(''); try { setDetail(await getInterviewEvaluationDetail(interview.id)); } catch (err) { setError(getApiErrorMessage(err, 'Evaluation detail is not available yet.')); } };
  return <Box><RecruiterNav /><Paper sx={{ p: 3 }}><Typography variant="h5" sx={{ fontWeight: 700 }}>Interview evaluations</Typography><Typography color="text.secondary" sx={{ mb: 2 }}>View submitted interviewer evaluations, transcript, and mock AI summary.</Typography>{error ? <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert> : null}{isLoading ? <CircularProgress /> : null}<Stack spacing={2}>{interviews.map((interview) => <Card key={interview.id}><CardContent><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" spacing={1}><Box><Typography variant="h6">{interview.application?.applicant?.full_name} • {interview.application?.job_title}</Typography><Typography color="text.secondary">{interview.interviewer?.full_name} • {formatDateTime(interview.scheduled_datetime)} • {interview.status}</Typography></Box><Stack direction="row" spacing={1}><Button onClick={() => openDetail(interview)} variant="outlined">View evaluation</Button><Button component={RouterLink} to={`/recruiter/applications/${interview.application?.id}/hiring-decision`}>Decision</Button></Stack></Stack></CardContent></Card>)}{detail ? <Paper variant="outlined" sx={{ p: 2 }}><Typography variant="h6">Evaluation for {detail.applicant_name}</Typography><Typography><strong>Total score:</strong> {detail.evaluation?.total_score ?? 'Not submitted'}</Typography><Typography><strong>Overall comment:</strong> {detail.evaluation?.overall_comment ?? '—'}</Typography><List>{detail.evaluation?.answers?.map((answer) => <ListItem key={answer.id}><ListItemText primary={`${answer.criterion?.criterion_name}: ${answer.score}`} secondary={answer.comment || answer.criterion?.description} /></ListItem>)}</List><Typography variant="h6">AI summary</Typography><Typography>{detail.ai_summary?.editable_summary_text || detail.ai_summary?.summary_text || 'No AI summary generated yet.'}</Typography><Typography variant="h6" sx={{ mt: 2 }}>Transcript</Typography><Typography whiteSpace="pre-line">{detail.transcript?.transcript_text || 'No transcript uploaded yet.'}</Typography></Paper> : null}</Stack></Paper></Box>;
}
