import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Grid, List, ListItem, ListItemText, Paper, Stack, Typography } from '@mui/material';
import { Link as RouterLink, useParams } from 'react-router-dom';
import { getJob, getJobFunnelAnalytics, getRankedCandidates } from '../../api/client.js';
import RecruiterNav from './RecruiterNav.jsx';
import { getApiErrorMessage, titleize } from './recruiterUtils.js';

export default function JobDetailPage() {
  const { jobId } = useParams();
  const [job, setJob] = useState(null); const [ranked, setRanked] = useState([]); const [funnel, setFunnel] = useState(null); const [error, setError] = useState(''); const [isLoading, setIsLoading] = useState(true);
  useEffect(() => { let active = true; Promise.allSettled([getJob(jobId), getRankedCandidates(jobId), getJobFunnelAnalytics(jobId)]).then(([jobResult, rankedResult, funnelResult]) => { if (!active) return; if (jobResult.status === 'fulfilled') setJob(jobResult.value); else setError(getApiErrorMessage(jobResult.reason, 'Unable to load job.')); if (rankedResult.status === 'fulfilled') setRanked(rankedResult.value); if (funnelResult.status === 'fulfilled') setFunnel(funnelResult.value); }).finally(() => active && setIsLoading(false)); return () => { active = false; }; }, [jobId]);
  return <Box><RecruiterNav /><Paper sx={{ p: 3 }}>{error ? <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert> : null}{isLoading ? <CircularProgress /> : null}{job ? <Stack spacing={3}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" spacing={2}><Box><Typography variant="h5" sx={{ fontWeight: 700 }}>{job.title}</Typography><Typography color="text.secondary">{job.organization_name} • {job.location}</Typography><Chip label={titleize(job.status)} color={job.status === 'open' ? 'success' : 'default'} sx={{ mt: 1 }} /></Box><Stack direction="row" spacing={1} useFlexGap flexWrap="wrap"><Button component={RouterLink} to={`/recruiter/jobs/${job.id}/edit`} variant="contained">Edit</Button><Button component={RouterLink} to={`/recruiter/jobs/${job.id}/requirements`} variant="outlined">Requirements</Button><Button component={RouterLink} to={`/recruiter/jobs/${job.id}/evaluation-form`} variant="outlined">Evaluation form</Button><Button component={RouterLink} to={`/recruiter/jobs/${job.id}/ranking`} variant="outlined">Ranked candidates</Button></Stack></Stack><Typography whiteSpace="pre-line">{job.description}</Typography><Grid container spacing={2}><Grid item xs={12} md={4}><Card><CardContent><Typography color="text.secondary">Applications</Typography><Typography variant="h4">{ranked.length}</Typography></CardContent></Card></Grid><Grid item xs={12} md={4}><Card><CardContent><Typography color="text.secondary">Employment</Typography><Typography>{job.employment_type}</Typography><Typography>{job.approximate_salary}</Typography></CardContent></Card></Grid><Grid item xs={12} md={4}><Card><CardContent><Typography color="text.secondary">Funnel</Typography><Typography>{JSON.stringify(funnel?.metrics ?? funnel ?? {})}</Typography></CardContent></Card></Grid></Grid><Box><Typography variant="h6">Requirements</Typography><List>{job.requirements?.map((req) => <ListItem key={req.id}><ListItemText primary={`${titleize(req.requirement_type)} (${req.weight_score})`} secondary={`${req.description} • Threshold ${req.minimum_threshold}`} /></ListItem>)}{!job.requirements?.length ? <ListItem><ListItemText primary="No requirements configured." /></ListItem> : null}</List></Box></Stack> : null}</Paper></Box>;
}
