import { useEffect, useState } from 'react';
import { Alert, Box, Button, Checkbox, FormControlLabel, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { useNavigate, useParams } from 'react-router-dom';
import { configureJobRequirements, getJob } from '../../api/client.js';
import RecruiterNav from './RecruiterNav.jsx';
import { getApiErrorMessage } from './recruiterUtils.js';

const blank = { requirement_type: 'skill', description: '', weight_score: '0.25', minimum_threshold: '0.50' };
export default function JobRequirementsPage() {
  const { jobId } = useParams(); const navigate = useNavigate(); const [requirements, setRequirements] = useState([blank]); const [normalize, setNormalize] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  useEffect(() => { getJob(jobId).then((job) => { if (job.requirements?.length) setRequirements(job.requirements.map(({ requirement_type, description, weight_score, minimum_threshold }) => ({ requirement_type, description, weight_score, minimum_threshold }))); }).catch((err) => setError(getApiErrorMessage(err, 'Unable to load requirements.'))); }, [jobId]);
  const update = (index, field, value) => setRequirements((items) => items.map((item, i) => i === index ? { ...item, [field]: value } : item));
  const save = async (event) => { event.preventDefault(); setError(''); setSuccess(''); try { await configureJobRequirements(jobId, { requirements, normalize_weights: normalize }); setSuccess('Requirements saved.'); } catch (err) { setError(getApiErrorMessage(err, 'Unable to save requirements.')); } };
  return <Box><RecruiterNav /><Paper sx={{ p: 3 }}><Typography variant="h5" sx={{ fontWeight: 700 }}>Job requirements</Typography>{error ? <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert> : null}{success ? <Alert severity="success" sx={{ mb: 2 }}>{success}</Alert> : null}<Box component="form" onSubmit={save}><Stack spacing={2}>{requirements.map((req, index) => <Paper key={index} variant="outlined" sx={{ p: 2 }}><Stack spacing={2}><TextField label="Type" select value={req.requirement_type} onChange={(e) => update(index, 'requirement_type', e.target.value)}><MenuItem value="skill">Skill</MenuItem><MenuItem value="experience">Experience</MenuItem><MenuItem value="education">Education</MenuItem><MenuItem value="certification">Certification</MenuItem><MenuItem value="other">Other</MenuItem></TextField><TextField label="Description" required value={req.description} onChange={(e) => update(index, 'description', e.target.value)} /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField label="Weight" type="number" inputProps={{ step: '0.01' }} value={req.weight_score} onChange={(e) => update(index, 'weight_score', e.target.value)} /><TextField label="Minimum threshold" type="number" inputProps={{ step: '0.01' }} value={req.minimum_threshold} onChange={(e) => update(index, 'minimum_threshold', e.target.value)} /></Stack><Button color="error" disabled={requirements.length === 1} onClick={() => setRequirements((items) => items.filter((_, i) => i !== index))}>Remove</Button></Stack></Paper>)}<FormControlLabel control={<Checkbox checked={normalize} onChange={(e) => setNormalize(e.target.checked)} />} label="Normalize weights to 1.0 automatically" /><Stack direction="row" spacing={1}><Button onClick={() => setRequirements((items) => [...items, blank])} variant="outlined">Add requirement</Button><Button type="submit" variant="contained">Save requirements</Button><Button onClick={() => navigate(`/recruiter/jobs/${jobId}`)}>Back to job</Button></Stack></Stack></Box></Paper></Box>;
}
