# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobrequisition'),
    ]

    position_status_choices = [('new_headcount', 'New Headcount'), ('backfill', 'Backfill')]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='approximate_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='core_responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='requirements_qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='custom_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='target_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='benefits_perks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='position_status',
            field=models.CharField(choices=position_status_choices, default='new_headcount', max_length=30),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='reason_for_hire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='impact_of_not_hiring',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='approximate_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='salary_range',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='core_responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='requirements_qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='custom_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='target_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='benefits_perks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='position_status',
            field=models.CharField(choices=position_status_choices, default='new_headcount', max_length=30),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='reason_for_hire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='impact_of_not_hiring',
            field=models.TextField(blank=True),
        ),
    ]
