# Generated by Django 5.2.15 on 2026-07-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_jobrequisition_details"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interviewevaluationform",
            options={
                "verbose_name": "Interview evaluation scorecard",
                "verbose_name_plural": "Interview evaluation scorecards",
            },
        ),
    ]
