# Generated by Django 5.2.16 on 2026-07-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_scorecard_verbose_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="application_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="vacancies",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("open", "Open"),
                    ("application_intake_closed", "Application Intake Closed"),
                    ("interviews_in_progress", "Interviews In Progress"),
                    ("ready_for_recommendation", "Ready for Hiring Recommendation"),
                    ("recommendation_pending", "Recommendation Pending HR Approval"),
                    ("recommendation_approved", "Recommendation Approved"),
                    (
                        "recommendation_rejected",
                        "Recommendation Rejected / Returned for Review",
                    ),
                    ("offer_stage", "Offer Stage / Offer Sent"),
                    ("closed_filled", "Closed - Filled"),
                    ("closed_no_hire", "Closed - No Hire"),
                    ("closed", "Closed (Legacy)"),
                ],
                default="draft",
                max_length=40,
            ),
        ),
    ]
