# Generated by Django 5.2.14 on 2026-06-02 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("withdrawn", "Withdrawn"),
                            ("screened", "Screened"),
                            ("screened_qualified", "Screened Qualified"),
                            ("screened_not_qualified", "Screened Not Qualified"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Rejected"),
                            ("interview_invited", "Interview Invited"),
                            ("interview_accepted", "Interview Accepted"),
                            ("interview_declined", "Interview Declined"),
                            ("interviewing", "Interviewing"),
                            ("evaluation_submitted", "Evaluation Submitted"),
                            ("decision_pending", "Decision Pending"),
                            ("hr_approved", "HR Approved"),
                            ("hr_rejected", "HR Rejected"),
                            ("offer_sent", "Offer Sent"),
                            ("offer_accepted", "Offer Accepted"),
                            ("offer_declined", "Offer Declined"),
                            ("hired", "Hired"),
                        ],
                        default="submitted",
                        max_length=30,
                    ),
                ),
                ("recruiter_remark", models.TextField(blank=True)),
                (
                    "semantic_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "skill_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "experience_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "education_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("score_explanation", models.JSONField(blank=True, default=dict)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        limit_choices_to={"role": "applicant"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.jobposting",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_stage",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("withdrawn", "Withdrawn"),
                            ("screened", "Screened"),
                            ("screened_qualified", "Screened Qualified"),
                            ("screened_not_qualified", "Screened Not Qualified"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Rejected"),
                            ("interview_invited", "Interview Invited"),
                            ("interview_accepted", "Interview Accepted"),
                            ("interview_declined", "Interview Declined"),
                            ("interviewing", "Interviewing"),
                            ("evaluation_submitted", "Evaluation Submitted"),
                            ("decision_pending", "Decision Pending"),
                            ("hr_approved", "HR Approved"),
                            ("hr_rejected", "HR Rejected"),
                            ("offer_sent", "Offer Sent"),
                            ("offer_accepted", "Offer Accepted"),
                            ("offer_declined", "Offer Declined"),
                            ("hired", "Hired"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "to_stage",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("withdrawn", "Withdrawn"),
                            ("screened", "Screened"),
                            ("screened_qualified", "Screened Qualified"),
                            ("screened_not_qualified", "Screened Not Qualified"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Rejected"),
                            ("interview_invited", "Interview Invited"),
                            ("interview_accepted", "Interview Accepted"),
                            ("interview_declined", "Interview Declined"),
                            ("interviewing", "Interviewing"),
                            ("evaluation_submitted", "Evaluation Submitted"),
                            ("decision_pending", "Decision Pending"),
                            ("hr_approved", "HR Approved"),
                            ("hr_rejected", "HR Rejected"),
                            ("offer_sent", "Offer Sent"),
                            ("offer_accepted", "Offer Accepted"),
                            ("offer_declined", "Offer Declined"),
                            ("hired", "Hired"),
                        ],
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_stage_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_history",
                        to="applications.jobapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.UniqueConstraint(
                fields=("applicant", "job"), name="unique_job_application"
            ),
        ),
    ]
