# Generated by Django 5.2.14 on 2026-06-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="extracted_education",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="extracted_experience",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="extracted_resume_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="extracted_skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
