# Generated by Django 5.2.15 on 2026-06-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_jobapplication_assigned_interviewer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationstagehistory",
            options={
                "ordering": ["-changed_at"],
                "verbose_name": "Application stage history",
                "verbose_name_plural": "Application stage histories",
            },
        ),
    ]
