# Generated by Django 5.2.15 on 2026-07-21

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_jobapplication_resume_validation_result'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobapplication',
            name='unique_job_application',
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(
                condition=~Q(status__in=['screened_not_qualified', 'rejected']),
                fields=('applicant', 'job'),
                name='unique_job_application',
            ),
        ),
    ]
