# Generated by Django 5.2.16 on 2026-07-24 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_jobapplication_application_resume_and_more"),
        ("jobs", "0013_jobposting_application_deadline_jobposting_vacancies_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerInvite",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("no_response", "No response"),
                            ("applied", "Applied for job"),
                            ("declined", "Declined"),
                        ],
                        default="no_response",
                        max_length=20,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        limit_choices_to={"role": "applicant"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_invites",
                        to="jobs.jobposting",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        limit_choices_to={"role": "recruiter"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_employer_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "applicant"),
                        name="unique_employer_invite_per_job_applicant",
                    )
                ],
            },
        ),
    ]
