# Generated by Django 5.2.14 on 2026-06-03 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0003_jobapplication_assigned_interviewer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HiringDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("hire", "Hire"), ("reject", "Reject")], max_length=10
                    ),
                ),
                ("recruiter_justification", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_hr_approval", "Pending HR Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_hr_approval",
                        max_length=30,
                    ),
                ),
                ("hr_head_justification", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hiring_decisions",
                        to="applications.jobapplication",
                    ),
                ),
                (
                    "hr_head",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "hr_head"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_hiring_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        limit_choices_to={"role": "recruiter"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_hiring_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offer_letter_file",
                    models.FileField(blank=True, null=True, upload_to="offer_letters/"),
                ),
                ("offer_message", models.TextField()),
                (
                    "offer_status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("respond_deadline", models.DateTimeField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_offers",
                        to="applications.jobapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
