# Generated by Codex on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='salary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary_currency',
            field=models.CharField(default='MYR', max_length=3),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='employment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='work_arrangement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='probation_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='benefits_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='candidate_response_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='offer_status',
            field=models.CharField(
                choices=[
                    ('sent', 'Sent'),
                    ('accepted', 'Accepted'),
                    ('declined', 'Declined'),
                    ('expired', 'Expired'),
                    ('withdrawn', 'Withdrawn'),
                ],
                default='sent',
                max_length=20,
            ),
        ),
    ]
