# Generated by Django 5.2.16 on 2026-07-17 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_jobapplication_resume_validation_result"),
        ("hiring", "0002_joboffer_realistic_terms"),
        ("jobs", "0013_jobposting_application_deadline_jobposting_vacancies_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobHiringDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("recommend_hire", "Recommend Hire"),
                            ("recommend_no_hire", "Recommend No Hire"),
                        ],
                        max_length=30,
                    ),
                ),
                ("justification", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_hr_approval", "Pending HR Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected / Returned for Review"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("hr_remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hiring_decisions",
                        to="jobs.jobposting",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        limit_choices_to={"role": "recruiter"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_job_hiring_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "hr_head"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_job_hiring_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobHiringDecisionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selection_order", models.PositiveIntegerField(default=1)),
                ("reason", models.TextField(blank=True)),
                ("selected_for_offer", models.BooleanField(default=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_hiring_decision_items",
                        to="applications.jobapplication",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="hiring.jobhiringdecision",
                    ),
                ),
            ],
            options={
                "ordering": ["selection_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("decision", "application"),
                        name="unique_job_decision_application",
                    )
                ],
            },
        ),
    ]
