# Generated by Django 5.2.15 on 2026-06-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewaisummary",
            name="summary_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
