# Generated by Django 5.2 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('evaluations', '0004_transcription_processing_status')]

    operations = [
        migrations.AlterField(
            model_name='interviewtranscript',
            name='processing_status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'), ('PROCESSING', 'Processing'),
                    ('COMPLETED', 'Completed'), ('FAILED', 'Failed'),
                    ('LOW_QUALITY', 'Low quality'),
                ],
                db_index=True, default='PENDING', max_length=12,
            ),
        ),
    ]
