# Generated by Django 5.2.16 on 2026-07-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("hr_head", "Hiring Manager"),
                    ("recruiter", "Recruiter"),
                    ("interviewer", "Interviewer"),
                ],
                max_length=20,
            ),
        ),
    ]
